[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
veilvote = "B9xuJHLGqgb2szy76qBUiXrAFpYgx4g7aUZrEDimsRFk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
